name: "web_app"
mode: "dev"
port: 8081
version: "v0.0.1"
machine_id: 1
start_time: "2000-05-09"
client_url: "*"

log:
  level: "info"
  filename: "./logs/web_app.log"
  max_size: 100
  max_age: 30
  max_backups: 7

mysql:
    host: "192.168.8.66"
    port: 3306
    user: "admin"
    password: "Mark1590"
    dbname: "workspace"
    max_idle_conns: 20
    max_conns: 100
file:
  filemaxsize: 2048
  savedir: "./static/upload/"
  httpurl: "http://127.0.0.1:8081"
  httpdir: "/static"
switch:
  username: "gyop"
  passtoken: "E@2wYZ!Asa"
